### ISSUE TITLE
undefined method `static_cache_control'

### ISSUE THREAD

**Issue by srghma** [eliotsykes/rails-static-router#1]
```
rails s
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `static_cache_control' for #<Rails::Application::Configuration:0x0000000476a8a0> (NoMethodError)
        from /home/bjorn/projects/ngrx-todolist/config/initializers/static_router.rb:64:in `initialize'
        from /home/bjorn/projects/ngrx-todolist/config/initializers/static_router.rb:81:in `new'
        from /home/bjorn/projects/ngrx-todolist/config/initializers/static_router.rb:81:in `static'
        from /home/bjorn/projects/ngrx-todolist/config/routes.rb:18:in `block in <top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:424:in `instance_exec'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:424:in `eval_block'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:406:in `draw'
        from /home/bjorn/projects/ngrx-todolist/config/routes.rb:1:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `block in load'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application/routes_reloader.rb:55:in `block in load_paths'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application/routes_reloader.rb:55:in `each'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application/routes_reloader.rb:55:in `load_paths'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application/routes_reloader.rb:18:in `reload!'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application/routes_reloader.rb:41:in `block in updater'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/activesupport-5.1.1/lib/active_support/file_update_checker.rb:81:in `execute'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application/routes_reloader.rb:42:in `updater'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application/routes_reloader.rb:31:in `execute_if_updated'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/initializable.rb:30:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/initializable.rb:58:in `run_initializers'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/application.rb:353:in `initialize!'
        from /home/bjorn/projects/ngrx-todolist/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:24:in `app'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:42:in `start'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:131:in `block in perform'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `tap'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `perform'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
        from /home/bjorn/projects/ngrx-todolist/bin/rails:9:in `require'
        from /home/bjorn/projects/ngrx-todolist/bin/rails:9:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
        from /home/bjorn/.rvm/gems/ruby-2.4.1@ngrx-todolist/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/bjorn/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/bjorn/projects/ngrx-todolist/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

```

**Comment by BjornMelgaard** [comment]
```
      def initialize(path)
        self.path = path
        # Only if you're on Rails 5+:
        self.file_handler = ActionDispatch::FileHandler.new(
          Rails.configuration.paths["public"].first
        )
        # Only if you're on Rails 4.2:
        # self.file_handler = ActionDispatch::FileHandler.new(
        #   Rails.configuration.paths["public"].first,
        #   Rails.configuration.static_cache_control
        # )
      end

```

[found here](https://www.questarter.com/q/routing-to-static-html-page-in-public-27_5631145.html)
